import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Web3AuthProvider } from "@/hooks/Web3AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-customDark min-w-screen">
        <Web3AuthProvider>
          <Navbar />
          {children}
        </Web3AuthProvider>
      </body>
    </html>
  );
}
